#!/usr/bin/env bash
# install_statusline.sh — Patches the user's ~/.claude/statusline-command.sh
# to include the ambient buddy segment. Plugin settings.json cannot register
# statusLine itself (see docs/solutions/developer-experience/
# claude-code-plugin-scaffolding-gotchas-2026-04-16.md), so the user's own
# Claude Code config is the only path. Always consent-gated, always reversible.
#
# Subcommands:
#   install    [--dry-run]   (default)
#   uninstall  [--dry-run]
#
# Discipline:
#   - Never overwrites an existing custom script — appends a guarded block.
#   - Always takes a timestamped backup before any write.
#   - On failed writes, exits non-zero (D10) so the user sees the problem.
#
# Test hooks:
#   $HOME override is honored for fixture-dir testing — every path resolves
#   under $HOME/.claude/.
#   BUDDY_INSTALL_ASSUME_YES=1 — skip interactive consent (used by tests).

set -uo pipefail

# Marker pair — uninstall finds and removes lines bracketed by these.
readonly _BUDDY_BEGIN_MARKER='# >>> buddy-plugin >>> (managed by /buddy:install-statusline)'
readonly _BUDDY_END_MARKER='# <<< buddy-plugin <<<'

_install_target() { printf '%s/.claude/statusline-command.sh' "$HOME"; }
_install_settings() { printf '%s/.claude/settings.json' "$HOME"; }
_install_backup_path() {
  local target="$1"
  local stamp
  stamp="$(date -u +%Y%m%dT%H%M%SZ 2>/dev/null || date +%s)"
  printf '%s.buddy-bak.%s' "$target" "$stamp"
}

# The block we append. Uses CLAUDE_PLUGIN_ROOT/CLAUDE_PLUGIN_DATA env vars
# if Claude Code exposes them; otherwise falls back to the standard
# inline-loaded paths (see plugin-data-path-inline-suffix solution doc).
_install_block() {
  cat <<EOF
$_BUDDY_BEGIN_MARKER
_BUDDY_ROOT="\${CLAUDE_PLUGIN_ROOT:-\$HOME/.claude/plugins/cache/buddy/current}"
_BUDDY_DATA="\${CLAUDE_PLUGIN_DATA:-\$HOME/.claude/plugins/data/buddy-inline}"
if [ -x "\$_BUDDY_ROOT/statusline/buddy-line.sh" ]; then
  buddy_part=\$(CLAUDE_PLUGIN_DATA="\$_BUDDY_DATA" bash "\$_BUDDY_ROOT/statusline/buddy-line.sh" </dev/null 2>/dev/null)
  [ -n "\$buddy_part" ] && printf ' %s' "\$buddy_part"
fi
$_BUDDY_END_MARKER
EOF
}

# Minimal new statusline script body when the user has nothing yet.
_install_minimal_script() {
  cat <<'EOF'
#!/usr/bin/env bash
# Generated by /buddy:install-statusline. Edit freely — the buddy block
# below is bracketed with markers so /buddy:install-statusline uninstall
# can remove it without touching the rest of this file.
EOF
  printf '\n'
  _install_block
}

_install_has_block() {
  local target="$1"
  [[ -f "$target" ]] || return 1
  grep -qF "$_BUDDY_BEGIN_MARKER" "$target"
}

_install_consent() {
  if [[ "${BUDDY_INSTALL_ASSUME_YES:-0}" == "1" ]]; then
    return 0
  fi
  local prompt="$1" reply
  printf '%s [y/N] ' "$prompt" >&2
  if ! IFS= read -r reply; then
    return 1
  fi
  case "$reply" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

# install [--dry-run]
_install_run() {
  local dry_run=0
  if [[ "${1:-}" == "--dry-run" ]]; then dry_run=1; fi

  local target settings block
  target="$(_install_target)"
  settings="$(_install_settings)"
  block="$(_install_block)"

  mkdir -p "$(dirname "$target")" 2>/dev/null || true

  if _install_has_block "$target"; then
    echo "buddy-plugin block already present in $target. Nothing to do."
    return 0
  fi

  if [[ -f "$target" ]]; then
    # Append-to-existing path.
    if (( dry_run )); then
      echo "--- Would append to $target ---"
      echo ""
      echo "$block"
      return 0
    fi
    echo "About to append the buddy segment to $target."
    echo "Diff:"
    echo ""
    echo "$block"
    echo ""
    if ! _install_consent "Continue?"; then
      echo "Cancelled — no changes made."
      return 0
    fi
    local backup
    backup="$(_install_backup_path "$target")"
    if ! cp -p "$target" "$backup"; then
      echo "buddy-install: failed to write backup $backup" >&2
      return 1
    fi
    if ! { printf '\n' && _install_block; } >> "$target"; then
      echo "buddy-install: failed to append block to $target" >&2
      return 1
    fi
    echo "Installed. Backup at $backup."
    echo "Restart Claude Code or wait one refresh cycle to see the buddy segment."
    return 0
  fi

  # Create-from-scratch path. Two writes, two consents.
  if (( dry_run )); then
    echo "--- Would create $target ---"
    echo ""
    _install_minimal_script
    echo ""
    echo "--- Would update $settings (set statusLine.command) ---"
    return 0
  fi
  echo "$target does not exist."
  echo "I can create a minimal one with the buddy segment, then update"
  echo "$settings to point Claude Code at it."
  echo ""
  if ! _install_consent "Create $target?"; then
    echo "Cancelled — no changes made."
    return 0
  fi
  if ! _install_minimal_script > "$target"; then
    echo "buddy-install: failed to create $target" >&2
    return 1
  fi
  chmod +x "$target" 2>/dev/null || true
  echo "Created $target."

  # Surface any pre-existing .statusLine before we overwrite it. Backup is
  # taken inside _install_update_settings, but the user deserves an in-band
  # warning so a drive-by "y" doesn't silently clobber their custom segment.
  if [[ -f "$settings" ]] && jq -e '.statusLine' "$settings" >/dev/null 2>&1; then
    local existing_cmd
    existing_cmd="$(jq -r '.statusLine.command // ""' "$settings" 2>/dev/null)"
    echo ""
    echo "Note: $settings already has a statusLine set:"
    echo "  command = \"$existing_cmd\""
    echo "Updating will REPLACE it (a backup will be written first). If you"
    echo "want to keep the existing command, decline and wire the buddy block"
    echo "into your current statusline script manually."
    echo ""
  fi
  if ! _install_consent "Update $settings to use this script as the statusLine?"; then
    echo "Skipped settings update. To enable manually, set"
    echo "  statusLine.command = \"$target\""
    echo "in $settings."
    return 0
  fi
  if ! _install_update_settings "$settings" "$target"; then
    return 1
  fi
  echo "Done. Restart Claude Code to pick up the new statusline."
  return 0
}

# Update ~/.claude/settings.json to point at $target. Refuses if the file
# exists and is not parseable JSON (safer to surface than to clobber).
_install_update_settings() {
  local settings="$1" target="$2"
  mkdir -p "$(dirname "$settings")" 2>/dev/null || true

  local existing='{}'
  if [[ -f "$settings" ]]; then
    if ! jq -e '.' "$settings" >/dev/null 2>&1; then
      echo "buddy-install: refusing to write — $settings is not valid JSON. Fix the file and re-run." >&2
      return 1
    fi
    local backup
    backup="$(_install_backup_path "$settings")"
    if ! cp -p "$settings" "$backup"; then
      echo "buddy-install: failed to back up $settings" >&2
      return 1
    fi
    echo "Backed up $settings to $backup."
    existing="$(cat "$settings")"
  fi

  local updated
  updated="$(jq --arg cmd "$target" \
    '.statusLine = {"type":"command","command":$cmd}' <<< "$existing")" || {
    echo "buddy-install: failed to update settings JSON" >&2
    return 1
  }

  local tmp
  tmp="$(mktemp "$settings.XXXXXX")" || {
    echo "buddy-install: failed to mktemp for settings write" >&2
    return 1
  }
  if ! printf '%s\n' "$updated" > "$tmp"; then
    rm -f "$tmp"
    echo "buddy-install: failed to write temp settings" >&2
    return 1
  fi
  if ! mv -f "$tmp" "$settings"; then
    rm -f "$tmp"
    echo "buddy-install: failed to mv temp settings into place" >&2
    return 1
  fi
  echo "Updated $settings."
}

# uninstall [--dry-run]
_install_uninstall() {
  local dry_run=0
  if [[ "${1:-}" == "--dry-run" ]]; then dry_run=1; fi

  local target
  target="$(_install_target)"
  if [[ ! -f "$target" ]]; then
    echo "$target does not exist. Nothing to uninstall."
    return 0
  fi
  if ! _install_has_block "$target"; then
    echo "No buddy-plugin block found in $target. Nothing to uninstall."
    return 0
  fi

  # Remove the block (inclusive of markers) by streaming line-by-line.
  local cleaned=""
  local skipping=0
  while IFS= read -r line || [[ -n "$line" ]]; do
    if (( ! skipping )) && [[ "$line" == "$_BUDDY_BEGIN_MARKER" ]]; then
      skipping=1
      continue
    fi
    if (( skipping )) && [[ "$line" == "$_BUDDY_END_MARKER" ]]; then
      skipping=0
      continue
    fi
    (( skipping )) && continue
    cleaned+="$line"$'\n'
  done < "$target"

  # Trim a single trailing blank line that the install path inserted before
  # the block. This keeps install → uninstall a true byte-identical round-trip
  # on files that had no trailing newline before install.
  cleaned="${cleaned%$'\n'}"
  # Detect: if the cleaned content ends with a blank line (i.e., two newlines
  # after stripping the single trailing one), drop one more.
  if [[ "$cleaned" == *$'\n' ]]; then
    cleaned="${cleaned%$'\n'}"
  fi

  if (( dry_run )); then
    echo "--- Would rewrite $target without the buddy block ---"
    return 0
  fi

  local backup
  backup="$(_install_backup_path "$target")"
  if ! cp -p "$target" "$backup"; then
    echo "buddy-install: failed to back up $target" >&2
    return 1
  fi

  if [[ -z "${cleaned//[$' \t\n']/}" ]]; then
    # File is empty or whitespace-only after removing the block.
    rm -f "$target"
    echo "Uninstalled. $target removed (was empty after block removal)."
    echo "Backup at $backup."
    return 0
  fi

  local tmp
  tmp="$(mktemp "$target.XXXXXX")" || {
    echo "buddy-install: failed to mktemp" >&2
    return 1
  }
  if ! printf '%s\n' "$cleaned" > "$tmp"; then
    rm -f "$tmp"
    echo "buddy-install: failed to write temp file" >&2
    return 1
  fi
  if ! mv -f "$tmp" "$target"; then
    rm -f "$tmp"
    echo "buddy-install: failed to replace $target" >&2
    return 1
  fi
  echo "Uninstalled. Backup at $backup."
}

_install_main() {
  # Pull global flags out of any position and forward only the subcommand
  # + flags the inner functions understand. Lets users type the args in
  # any order and lets the slash-command dispatch path recover when
  # interactive consent isn't available (--yes bypass).
  local subcmd=""
  local -a passthrough=()
  local arg
  for arg in "$@"; do
    case "$arg" in
      --yes|-y)
        export BUDDY_INSTALL_ASSUME_YES=1
        ;;
      install|uninstall|--help|-h|help)
        # Subcommand keywords. First one wins; ignore later duplicates.
        [[ -z "$subcmd" ]] && subcmd="$arg"
        ;;
      --dry-run)
        # Top-level synonym for `install --dry-run` when no subcommand was
        # given. If install/uninstall was named, just forward through.
        passthrough+=("--dry-run")
        ;;
      *)
        echo "Unknown argument: $arg" >&2
        echo "Usage: install-statusline.sh [install|uninstall] [--dry-run] [--yes|-y]" >&2
        return 1
        ;;
    esac
  done

  # Default to install when no subcommand was named.
  [[ -z "$subcmd" ]] && subcmd="install"

  case "$subcmd" in
    install)
      _install_run "${passthrough[@]}"
      ;;
    uninstall)
      _install_uninstall "${passthrough[@]}"
      ;;
    --help|-h|help)
      cat <<EOF
Usage: install-statusline.sh [install|uninstall] [--dry-run] [--yes|-y]

  install      Patch ~/.claude/statusline-command.sh to include the buddy
               segment. Asks for consent on stdin. Always backs up first.
  uninstall    Remove the buddy block. Always backs up first.
  --dry-run    Print the planned change; do not write.
  --yes, -y    Skip the consent prompt. Required when invoked from a
               slash-command dispatch (where stdin is empty), since
               otherwise the consent prompt EOFs and the script cancels.
EOF
      ;;
  esac
}

_install_main "$@"
